<a href="https://colab.research.google.com/github/utsavbheda13/CE011_UtsavBheda_ML/blob/main/Lab01/011_Lab_01_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [20]:
import numpy as np
import pandas as pd

In [21]:
# two matrics
array1 = np.array([[11, 15, 13],[32, 17, 25]])
array2 = np.array([[30,-5],[15, 41],[4, -11]])
print(array1)
print(array2)

[[11 15 13]
 [32 17 25]]
[[ 30  -5]
 [ 15  41]
 [  4 -11]]


In [22]:
#randomly initialize array
arr1 = np.random.rand(3, 2)
arr2 = np.random.rand(2,3)
print(arr1)
print(arr2)

[[0.34374671 0.82736715]
 [0.41544763 0.36309213]
 [0.04793476 0.53506995]]
[[0.54072597 0.92385175 0.02674457]
 [0.4714628  0.45325397 0.09711347]]


In [23]:
# perform matrix multiplication
mul = np.dot(array1, array2)
print(mul)

[[ 607  417]
 [1315  262]]


In [24]:
# perform element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res) 

[[607, 417], [1315, 262]]


In [25]:
# mean of first matrix
mean = np.mean(array1)
print(mean)

18.833333333333332


In [26]:
main_data = pd.read_csv("/content/drive/MyDrive/SEM7/ML/Lab1/mtcars.csv")

In [27]:
del main_data['model']
# meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())


        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
